export const FETCH_USER = {
  ACTION: 'app/USER/FETCH_USER_ACTION',
  PENDING: 'app/USER/FETCH_USER_LOAD',
  SUCCESS: 'app/USER/FETCH_USER_SUCCESS',
  ERROR: 'app/USER/FETCH_USER_ERROR',
}

export const REGISTER_USER = {
  ACTION: 'app/USER/REGISTER_USER_ACTION',
  PENDING: 'app/USER/REGISTER_USER_LOAD',
  SUCCESS: 'app/USER/REGISTER_USER_SUCCESS',
  ERROR: 'app/USER/REGISTER_USER_ERROR',
}